feat(BUX-596): change code owners
bitcoin-sv/spv-wallet pull request #483
Opened 2024-03-01 09:24 UTC by pawellewandowski98

# Pull Request Checklist

- [ ] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/bitcoin-sv/spv-wallet/blob/main/.github/CODE_STANDARDS.md)
- [ ] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/bitcoin-sv/spv-wallet/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [ ] 📝 I have used conventional commits.
- [ ] 📗 I have updated any related documentation.
- [ ] 💾 PR was issued based on the Github or Jira issue.

2024-03-01 09:50 UTC, arkadiuszos4chain approved these changes

2024-03-01 10:16 UTC, dorzepowski requested changes

2024-03-01 10:16 UTC, dorzepowski commented on .github/CODEOWNERS
Remove those lines like in the others

2024-03-04 10:51 UTC, pawellewandowski98 commented on .github/CODEOWNERS
Done

2024-03-04 11:00 UTC, dorzepowski approved these changes

2024-03-04 11:01 UTC, merged