feat(spv-1062) removing new relic
bitcoin-sv/spv-wallet pull request #719
Opened 2024-10-03 08:23 UTC by ac4ch

# Pull Request Checklist

- [ ] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/bitcoin-sv/spv-wallet/blob/main/.github/CODE_STANDARDS.md)
- [ ] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/bitcoin-sv/spv-wallet/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [ ] 📝 I have used conventional commits.
- [ ] 📗 I have updated any related documentation.
- [ ] 💾 PR was issued based on the Github or Jira issue.

2024-10-03 08:49 UTC, Nazarii-4chain approved these changes
LGTM

2024-10-03 10:49 UTC, dorzepowski requested changes

2024-10-03 10:59 UTC, chris-4chain requested changes

2024-10-03 10:59 UTC, chris-4chain commented on cmd/main.go
**General comment**
I can still see a lot of occurrences of the keyword `relic`.
![image](https://github.com/user-attachments/assets/b6a04ec5-6444-4377-ab11-64204cebc133)

2024-10-04 05:35 UTC, dorzepowski commented on engine/interface.go
> +	chainmodels "github.com/bitcoin-sv/spv-wallet/engine/chain/models"
why this change?

2024-10-04 05:43 UTC, dorzepowski commented on engine/interface.go
> +	chainmodels "github.com/bitcoin-sv/spv-wallet/engine/chain/models"
ok, now I know. It's fine

2024-10-04 05:43 UTC, dorzepowski approved these changes

2024-10-04 05:44 UTC, nonus25 commented on engine/interface.go
> +	chainmodels "github.com/bitcoin-sv/spv-wallet/engine/chain/models"
np :) good

2024-10-04 07:54 UTC, chris-4chain approved these changes

2024-10-04 08:11 UTC, merged