feat(SPV-1248) add domain check for paymail entry
bitcoin-sv/spv-wallet pull request #828
Opened 2024-12-20 11:09 UTC by cain4chain

- feat(paymail) add checkPaymailDomain function for domain validation 
- feat(error) add error definition to engine code for invalid domain
- chore(paymailCreateAddress) add logic for domain validation check

# Pull Request Checklist

- [ ] 📖 I created my PR using provided  : [CODE_STANDARDS](https://github.com/bitcoin-sv/spv-wallet/blob/main/.github/CODE_STANDARDS.md)
- [ ] 📖 I have read the short Code of Conduct: [CODE_OF_CONDUCT](https://github.com/bitcoin-sv/spv-wallet/blob/main/.github/CODE_OF_CONDUCT.md)
- [ ] 🏠 I tested my changes locally.
- [ ] ✅ I have provided tests for my changes.
- [ ] 📝 I have used conventional commits.
- [ ] 📗 I have updated any related documentation.
- [ ] 💾 PR was issued based on the Github or Jira issue.

2024-12-20 11:41 UTC, chris-4chain approved these changes

2024-12-20 11:41 UTC, chris-4chain commented on actions/admin/paymail_addresses_old.go
> +	}
This is duplicated code.
But since we plan to remove the "old" handlers soon (I believe 🙈), it is totally fine to me 👍

2025-01-07 09:49 UTC, dorzepowski commented on actions/admin/paymail_addresses.go
> +		if !checkPaymailDomain(actualDomain, config.Paymail.Domains) {
Maybe we could simply use `slices.Contains`
```suggestion
		if !slices.Contains(config.Paymail.Domains, actualDomain) {
```

2025-01-07 15:16 UTC, dorzepowski requested changes

2025-01-07 15:16 UTC, dorzepowski commented on actions/admin/paymail_addresses.go
> +	config := reqctx.AppConfig(c)
IMHO PR is a good opportunity to write some endpoint tests for create paymail address endpoint.

2025-01-09 10:30 UTC, cainnusti commented on actions/admin/paymail_addresses.go
> +		if !checkPaymailDomain(actualDomain, config.Paymail.Domains) {
ok I will add this and test the change locally.

2025-01-15 07:37 UTC, dorzepowski approved these changes

2025-01-15 13:42 UTC, chris-4chain approved these changes

2025-01-16 06:37 UTC, merged